---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: my-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-proxy
  template:
    metadata:
      labels:
      app: my-proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
...                
